USE [master]
GO

/****** Object:  Database [list]    Script Date: 12/2/2018 8:18:58 PM ******/
CREATE DATABASE [list]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'list', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL11.SSQLSERVER\MSSQL\DATA\list.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'list_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL11.SSQLSERVER\MSSQL\DATA\list_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [list] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [list].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [list] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [list] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [list] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [list] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [list] SET ARITHABORT OFF 
GO

ALTER DATABASE [list] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [list] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [list] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [list] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [list] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [list] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [list] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [list] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [list] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [list] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [list] SET  DISABLE_BROKER 
GO

ALTER DATABASE [list] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [list] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [list] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [list] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [list] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [list] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [list] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [list] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [list] SET  MULTI_USER 
GO

ALTER DATABASE [list] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [list] SET DB_CHAINING OFF 
GO

ALTER DATABASE [list] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [list] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [list] SET  READ_WRITE 
GO


